project:
  type: website
  output-dir: docs
  resources: 
     - Resume.pdf
website:
  title: "Dami Bello's Webpage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
    tools:
      - icon: twitter
        href: https://twitter.com/damibello
      - icon: github
        href: https://github.com/Damib12
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Dami Bello"

format:
  html:
    theme: cerulean
    toc: true

editor: source

